swagger: '2.0'
info:
  version: 1.0.0
  title: 'OreumIO James REST API'
  description: >
    OreumIO James API 는 시스템 관리자가 관리할 수 있게 해줍니다.
host: localhost:8083
paths:
  /clients.do:
    get:
      description: |
        고객 정보를 검색한다.
      security:
        - basic: []
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Client'
    post:
      description: |
        고객을 등록한다.
      security:
        - basic: []
      parameters:
        - name: body
          in: body
          description: 클라이언트 오브젝트
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Client'
  /clients/{clientId}.do:
    get:
      description: |
        고객의 정보를 얻는다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/clientId'
      responses:
        '200':
          description: Successful response
  /clients/{clientId}/changeDisplayName.do:
    post:
      description: |
        고객의 표시명을 변경한다.
      security:
        - basic: []
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/clientId'
        - name: displayName
          in: formData
          description: 클라이언트 쿼타
          required: true
          type: string
      responses:
        '200':
          description: Successful response
  /clients/{clientId}/changeQuota.do:
    post:
      description: |
        고객의 쿼타를 변경한다.
      security:
        - basic: []
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/clientId'
        - name: quota
          in: formData
          description: 클라이언트 쿼타
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
  /clients/{clientId}/changeState.do:
    post:
      description: |
        고객의 상태를 변경한다.
      security:
        - basic: []
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/clientId'
        - name: state
          in: formData
          description: 클라이언트 상태
          required: true
          type: string
      responses:
        '200':
          description: Successful response
  /clients/{clientId}/domains.do:
    get:
      description: |
        고객 도메인 목록을 구한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/clientId'
      responses:
        '200':
          description: Successful response
    post:
      description: |
        고객이 사용할 도메인을 등록한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/clientId'
        - name: domain
          in: formData
          description: 클라이언트 도메인
          required: true
          type: string
      responses:
        '200':
          description: Successful response
  /clients/{clientId}/domains/{domainId}.do:
    delete:
      description: |
        고객 도메인을 삭제한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/clientId'
        - $ref: '#/parameters/domainId'
      responses:
        '200':
          description: Successful response
definitions:
  Client:
    type: object
    properties:
      clientId:
        type: string
        description: 고객 아이디
      displayName:
        type: string
        description: 고객 표시명
      quota:
        type: integer
        description: 고객 쿼타
      state:
        type: string
        description: 고객 상태. 정상, 정지, 삭제.
  Group:
    type: object
    properties:
      groupId:
        type: string
        description: 그룹 아이디
      clientId:
        type: string
        description: 고객 아이디
      description:
        type: string
        description: 그룹 설명
      displayName:
        type: string
        description: 그룹 표시명
      quota:
        type: integer
        format: int32
        description: 용량
      config:
        type: string
        description: 그룹 설정
      state:
        type: string
        description: 그룹 상태. 정상, 정지, 삭제.
      domainName:
        type: string
        description: 주 도메인명
      secondaryDomainNames:
        type: array
        items:
          type: string
          description: 도메인명.
parameters:
  clientId:
    name: clientId
    in: path
    description: 고객 아이디
    required: true
    type: string
  groupId:
    name: groupId
    in: path
    description: 그룹 아이디
    required: true
    type: string
  domainId:
    name: domainId
    in: path
    description: 도메인 아이디
    required: true
    type: string
  secDomainId:
    name: secDomainId
    in: path
    description: 부 도메인 아이디
    required: true
    type: string
securityDefinitions:
  basic:
    type: basic
    description: HTTP 인증
