swagger: '2.0'
info:
  version: 1.0.0
  title: 'OreumIO James GA API'
  description: >
    OreumIO James GA API 는 그룹관리자가 그룹을 관리할 수 있게 해줍니다.
    그룹 설정 관리
    사용자 관리
    조직 관리
host: localhost:8083
produces:
  - application/json
  - text/html
  - text/plain
paths:
  /group.do:
    get:
      description: |
        그룹 정보를 조회한다.
      security:
        - basic: []
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Group'
  /group/getQuotaUsage.do:
    post:
      description: |
        그룹의 사용량 실적을 조회한다.
      security:
        - basic: []
      responses:
        '200':
          description: Successful response
  /group/changeConfig.do:
    post:
      description: |
        그룹 설정을 변경한다.
      security:
        - basic: []
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: config
          in: formData
          description: 그룹 설정
          required: true
          type: string
      responses:
        '200':
          description: Successful response
  /users.do:
    get:
      description: |
        사용자를 검색한다. 사용자 사용량 실적을 포함.
      security:
        - basic: []
      parameters:
        - name: pageNo
          in: query
          description: 페이지 번호
          type: integer
        - name: pageSize
          in: query
          description: 페이지 크기
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      description: |
        사용자를 등록한다.
      security:
        - basic: []
      parameters:
        - name: body
          in: body
          description: 사용자 오브젝트
          required: false
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Successful response
  /users/{userId}.do:
    get:
      description: |
        사용자의 정보를 얻는다. 사용량 실적을 포함.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/User'
  /users/{userId}/suspend.do:
    post:
      description: |
        사용자를 정지시킨다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
  /users/{userId}/resume.do:
    post:
      description: |
        사용자를 재개시킨다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
  /users/{userId}/getQuota.do:
    post:
      description: |
        사용자의 실적 용량을 취득한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
  /users/{userId}/changeQuota.do:
    post:
      description: |
        사용자의 계획 용량을 변경한다.
      security:
        - basic: []
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: '#/parameters/userId'
        - name: quota
          in: formData
          description: 사용자 계획 용량
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
  /users/{userId}/roles.do:
    get:
      description: |
        사용자 역할을 검색한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Role'
    post:
      description: |
        사용자 역할을 부여한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
        - name: body
          in: body
          description: 사용자 역할 오브젝트
          required: false
          schema:
            $ref: '#/definitions/Role'
      responses:
        '200':
          description: Successful response
  /users/{userId}/roles/{roleId}.do:
    delete:
      description: |
        사용자 역할을 박탈한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/userId'
        - $ref: '#/parameters/roleId'
      responses:
        '200':
          description: Successful response
  /orgs.do:
    get:
      description: |
        조직을 검색한다.
      security:
        - basic: []
      parameters:
        - name: pageNo
          in: query
          description: 페이지 번호
          type: integer
        - name: pageSize
          in: query
          description: 페이지 크기
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Org'
    post:
      description: |
        조직을 등록한다.
      security:
        - basic: []
      parameters:
        - name: body
          in: body
          description: 조직 오브젝트
          required: false
          schema:
            $ref: '#/definitions/Org'
      responses:
        '200':
          description: Successful response
  /orgs/{orgId}.do:
    get:
      description: |
        조직의 정보를 얻는다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Org'
    delete:
      description: |
        조직을 삭제한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
      responses:
        '200':
          description: Successful response
  /orgs/{orgId}/orgUnits.do:
    get:
      description: |
        하위 조직 단위를 검색한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - name: parentOrgUnitId
          in: query
          description: 상위 조직 단위 아이디
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/OrgUnit'
    post:
      description: |
        조직 단위를 등록한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - name: body
          in: body
          description: 조직 단위 오브젝트
          required: false
          schema:
            $ref: '#/definitions/OrgUnit'
      responses:
        '200':
          description: Successful response
  /orgs/{orgId}/orgUnits/{orgUnitId}.do:
    get:
      description: |
        조직 단위의 정보를 얻는다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - $ref: '#/parameters/orgUnitId'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/OrgUnit'
    delete:
      description: |
        조직 단위를 삭제한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - $ref: '#/parameters/orgUnitId'
      responses:
        '200':
          description: Successful response
  /orgs/{orgId}/orgUnits/{orgUnitId}/members.do:
    get:
      description: |
        조직 단위의 사용자를 검색한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - $ref: '#/parameters/orgUnitId'
        - name: inclusive
          in: query
          description: 하위 조직단위 포함 여부
          type: boolean
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/OrgUnitUser'
    post:
      description: |
        조직 단위의 사용자를 등록한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - $ref: '#/parameters/orgUnitId'
        - name: body
          in: body
          description: 사용자 오브젝트
          schema:
            $ref: '#/definitions/OrgUnitUser'
      responses:
        '200':
          description: Successful response
  /orgs/{orgId}/orgUnits/{orgUnitId}/members/{userId}.do:
    get:
      description: |
        조직 단위의 사용자의 정보를 얻는다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - $ref: '#/parameters/orgUnitId'
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/OrgUnitUser'
    delete:
      description: |
        조직 단위의 사용자를 삭제한다.
      security:
        - basic: []
      parameters:
        - $ref: '#/parameters/orgId'
        - $ref: '#/parameters/orgUnitId'
        - $ref: '#/parameters/userId'
      responses:
        '200':
          description: Successful response
definitions:
  Group:
    type: object
    properties:
      id:
        type: string
        description: 그룹 아이디
      clientId:
        type: string
        description: 고객 아이디
      description:
        type: string
        description: 그룹 설명
      displayName:
        type: string
        description: 그룹 표시명
      userName:
        type: string
        description: 고객 사용자 아이디
      password:
        type: string
        description: 패스워드
      alg:
        type: string
        description: 패스워드 알고리즘
      host:
        type: string
        description: 접속 호스트
      quota:
        type: integer
        format: int32
        description: 용량
      config:
        type: string
        description: 그룹 설정
      state:
        type: string
        description: 그룹 상태. 정상, 정지, 삭제.
      domainName:
        type: string
        description: 주 도메인명
      secondaryDomainNames:
        type: array
        items:
          type: string
          description: 도메인명.
  User:
    type: object
    properties:
      id:
        type: string
        description: 사용자 아이디
      groupId:
        type: string
        description: 그룹 아이디
      userName:
        type: string
        description: 사용자명. 이메일 주소의 지역부.
      host:
        type: string
        description: 도메인명. 이메일 주소의 도메인부. 인증 시에 사용하는 호스트로 포트를 포함함.
      displayName:
        type: string
        description: 사용자 표시명
      socketEnabled:
        type: string
        description: POP3/IMAP 사용여부.
      state:
        type: string
        description: 사용자 상태. 정상(N), 정지(R), 삭제(D).
      quota:
        type: integer
        format: int32
        description: 계획 용량
      serverConfig:
        type: string
        description: 서버를 위한 사용자 설정
      clientConfig:
        type: string
        description: 클라이언트를 위한 사용자 설정
  Role:
    type: object
    properties:
      id:
        type: string
        description: 역할 아이디
      displayName:
        type: string
        description: 역할 표시명
  Org:
    type: object
    properties:
      id:
        type: string
        description: 조직 아이디. 0 회사, 1 부서, 2 직위, 3 직무, 4 직책, 5 기타
      groupId:
        type: string
        description: 그룹 아이디
      displayName:
        type: string
        description: 조직 표시명
  OrgUnit:
    type: object
    properties:
      id:
        type: string
        description: 조직 단위 아이디
      orgId:
        type: string
        description: 조직 아이디
      displayName:
        type: string
        description: 조직 표시명
      parentOrgNodeId:
        type: string
        description: 부모 조직 단위 아이디
  OrgUnitUser:
    type: object
    properties:
      id:
        type: string
        description: 조직 단위 아이디
      orgId:
        type: string
        description: 조직 아이디
      userId:
        type: string
        description: 사용자 아이디
parameters:
  userId:
    name: userId
    in: path
    description: 사용자 아이디
    required: true
    type: string
  roleId:
    name: roleId
    in: path
    description: 사용자 역할 아이디
    required: true
    type: string
  orgId:
    name: orgId
    in: path
    description: 조직 아이디
    required: true
    type: string
  orgUnitId:
    name: orgUnitId
    in: path
    description: 조직 단위 아이디
    required: true
    type: string
securityDefinitions:
  basic:
    type: basic
    description: HTTP 인증
